---
- name: Install Apache Modules
  become: yes
  apache2_module: state=present name={{ item }}
  with_items: "{{ apache_modules }}"
  tags: apache

- name: Enable Modules
  become: yes
  command: /usr/sbin/a2enmod {{ item }}
  with_items: "{{ apache_modules }}"
  tags: apache

- name: Stat 000-default.conf
  stat: path=/etc/apache2/sites-available/000-default.conf
  register: apache_default_site_exists

- name: Disable 000-default
  become: yes
  shell: /usr/sbin/a2dissite 000-default
  when: apache_default_site_exists.stat.exists == True
  tags: apache

- name: Remove 000-default.conf
  become: yes
  file: path=/etc/apache2/sites-available/000-default.conf state=absent
  when: apache_default_site_exists.stat.exists == True
  notify: restart apache
  tags: apache

- name: Remove /var/www/html
  become: yes
  file: path=/var/www/html state=absent
  notify: restart apache
  tags: apache
