---
- name: PHP | Adjust php.ini memory_limit
  sudo: yes
  lineinfile: dest={{ item }}
              regexp='memory_limit'
              line='memory_limit = {{ php_ini_memory_limit }}'
  with_items:
    - /etc/php5/apache2/php.ini
    - /etc/php5/cli/php.ini
  tags: PHP

- name: PHP | Adjust php.ini xdebug
  sudo: yes
  lineinfile: dest=/etc/php5/mods-available/xdebug.ini
              regexp='^xdebug\.max_nesting_level'
              line='xdebug.max_nesting_level = {{ php_ini_xdebug_max_nesting_level }}'
  tags: php
