---
- name: Drupal8 | Install Drupal
  sudo: yes
  shell: cd /var/www/dev1.d8.local && provisioning/bin/install.sh --quiet
  tags: drupal8

- name: Drupal8 | Install Apache vhost
  sudo: yes
  template: src=dev1.d8.local.conf dest=/etc/apache2/sites-available/dev1.d8.local.conf
  tags: drupal8

- name: Drupal8 | Copy settings.php
  sudo: yes
  template: src=settings.php dest=/var/www/dev1.d8.local/web/sites/default/settings.php
  tags: drupal8

- name: Drupal8 | Stat dev1.d8.local.conf
  stat: path=/etc/apache2/sites-enabled/dev1.d8.local.conf
  register: drupal8_vhost_exists
  tags: drupal8

- name: Drupal8 | Enable Drupal8 vhost
  sudo: yes
  shell: /usr/sbin/a2ensite dev1.d8.local
  when: drupal8_vhost_exists.stat.exists == False
  tags: drupal8

- name: Drupal8 | Restart Apache
  sudo: yes
  service: name=apache2 state=restarted
  tags: drupal8
