---
- name: Drupal8 | Install Apache vhost
  sudo: yes
  template: src=drupal8-skeleton.conf dest=/etc/apache2/sites-available/drupal8-skeleton.conf
  tags: drupal8

- name: Drupal8 | Stat Drupal8-skeleton.conf
  stat: path=/etc/apache2/sites-enabled/drupal8-skeleton.conf
  register: drupal8_vhost_exists
  tags: drupal8

- name: Drupal8 | Enable Drupal8 vhost
  sudo: yes
  shell: /usr/sbin/a2ensite drupal8-skeleton
  when: drupal8_vhost_exists.stat.exists == False
  tags: drupal8

- name: Drupal8 | Restart Apache
  sudo: yes
  service: name=apache2 state=restarted
  tags: drupal8