---
- name: Check drush existence
  stat: path=/home/vagrant/.config/composer/vendor/bin/drush
  register: drush_binary
  tags: drush

- name: Install drush
  shell: composer global require --prefer-dist drush/drush
  when: drush_binary.stat.exists == False
  tags: drush
