---
- name: Drush | Remove apt version
  sudo: yes
  apt: name=drush state=absent
  tags: drush

- name: Drush | Stat drush
  stat: path=/home/vagrant/.config/composer/vendor/bin/drush
  register: drush_binary
  tags: drush

- name: Drush | Install drush@dev-master
  shell: composer global require drush/drush:dev-master
  when: drush_binary.stat.exists == False
  tags: drush

- name: Drush | Update drush@dev-master
  shell: composer global update drush/drush
  when: drush_binary.stat.exists == True
  tags: drush

- name: Drush | Update .bashrc
  lineinfile: dest=/home/vagrant/.bashrc
              regexp="export PATH=\"$HOME/.config/composer/vendor/bin:$PATH\""
              line="export PATH=\"$HOME/.config/composer/vendor/bin:$PATH\""
              insertafter=EOF
              state=present
  tags: drush
